### ISSUE TITLE
下载笔记中远程图片至本地功能无法使用

### ISSUE THREAD

**Issue by Ausli** [chenfeicqq/obsidian-attachment-manager#2]
![image](https://github.com/chenfeicqq/obsidian-attachment-manager/assets/70201547/0e2fca6e-fe9f-42d5-984e-e29f5046fc48)
使用回车没有任何反应

**Comment by chenfeicqq** [comment]
下载必须先打开笔记，下载的时候会解析当前打开的笔记内容，找到远程的图片链接，并下载。

我在 md 文件中使用下面的链接是可以下载的

```
![](https://user-images.githubusercontent.com/70201547/266799062-0e2fca6e-fe9f-42d5-984e-e29f5046fc48.png)
```

能贴下你的远程图片的链接吗？方便我复现这个问题

**Comment by Ausli** [comment]
![1-ssh-install-1panel.png (2010×396) (public.oss-cn-shanghai.elyart.cn)](https://public.oss-cn-shanghai.elyart.cn/extend/discuss.flarum.org.cn/1Panel-%E9%9D%A2%E6%9D%BF%E5%AE%89%E8%A3%85-Flarum/pic/1-ssh-install-1panel.png)

**Comment by chenfeicqq** [comment]
我明白问题出在哪里了，和链接无关。我马上发一个版本修复下。

**Comment by chenfeicqq** [comment]
问题已修复，升级到 1.1.2 即可

https://github.com/chenfeicqq/obsidian-attachment-manager/releases/tag/1.1.2
