### ISSUE TITLE
文件夹内的笔记附件，无法根据笔记名自动重命名。

### ISSUE THREAD

**Issue by Novice-level** [chenfeicqq/obsidian-attachment-manager#3]
如标题，在我这里使用，不知道为什么，会导致文件夹内的笔记附件都无法自动重命名，文件夹外的根目录位置的笔记，就可以正常自动命名。😭
我尝试过新建库，也是同样的问题。

**Comment by chenfeicqq** [comment]
能贴一下插件的配置，并给一个示例吗？

我没法重现你的问题

**Comment by chenfeicqq** [comment]
@Novice-level 你的这个问题应该和 #5 是同一个问题，

https://github.com/chenfeicqq/obsidian-attachment-manager/releases/tag/1.1.1

已修复，升级到 1.1.1 版本
