### ISSUE TITLE
希望不要自动修改设置-内部链接类型

### ISSUE THREAD

**Issue by Lepton-Lee** [chenfeicqq/obsidian-attachment-manager#4]
希望不要在每次启动的自动修改内部链接类型为【基于当前笔记的相对路径】，相对路径比较长，会导致在笔记内插入内部链接后比较丑陋。我每次启动都手动将该选项修改为【尽可能简短的形式】，似乎也没有对插件运行造成影响？

**Comment by chenfeicqq** [comment]
我周末改一下，启动的时候不自动修改内部链接的类型。

**Comment by chenfeicqq** [comment]
https://github.com/chenfeicqq/obsidian-attachment-manager/releases/tag/1.1.1

已修复，升级到 1.1.1 版本
