### ISSUE TITLE
移动md文件的时候，附件文件夹不会跟着一起移动

### ISSUE THREAD

**Issue by jiajiala** [chenfeicqq/obsidian-attachment-manager#5]
[Custom Attachment location](https://github.com/RainCat1998/obsidian-custom-attachment-location#obsidian-custom-attachment-location)
类似这个插件，可以将附件文件夹随着md一起移动到正确的文件夹下

**Comment by chenfeicqq** [comment]
会自动移动的啊，下面2个选项开启了吗？

<img width="797" alt="image" src="https://github.com/chenfeicqq/obsidian-attachment-manager/assets/2122266/06cf40d0-7f0c-4480-abd0-8fb9ed710d53">

**Comment by chenfeicqq** [comment]
能贴一下你的插件配置，以及具体的目录树吗？

<img width="292" alt="image" src="https://github.com/chenfeicqq/obsidian-attachment-manager/assets/2122266/7847927c-c28c-49c7-b1f3-5bcb084f5274">

我将 笔记 在 Untitled 及 Untitled 1 两个文件夹进行移动，附件文件夹 “笔记.md_Attachments” 都是可以正常跟着移动的。

**Comment by jiajiala** [comment]
![image](https://github.com/chenfeicqq/obsidian-attachment-manager/assets/73203026/67a14a3c-93d9-422c-9ad1-844c5d70eda3)

**Comment by chenfeicqq** [comment]
我看下怎么兼容下

**Comment by chenfeicqq** [comment]
https://github.com/chenfeicqq/obsidian-attachment-manager/releases/tag/1.1.1

已修复，升级到 1.1.1 版本
