### ISSUE TITLE
希望使用远程下载图片后自动重命名

### ISSUE THREAD

**Issue by Ausli** [chenfeicqq/obsidian-attachment-manager#8]
下载图片后程序不会自己重命名，需要自己再改一次

**Comment by chenfeicqq** [comment]
<img width="1112" alt="image" src="https://github.com/chenfeicqq/obsidian-attachment-manager/assets/2122266/56477fba-e27e-4c64-85ce-e13cd7d77382">

下载后会自动按照 笔记名-时间戳 的格式进行重命名的啊，能截图看下吗？

**Comment by Ausli** [comment]
https://github.com/chenfeicqq/obsidian-attachment-manager/assets/70201547/b28bd467-13f9-4e90-a749-ad3a4ddf8bac

**Comment by Ausli** [comment]
不是的，希望下载完后我md的链接从https链接变成我本地obsidian链接

**Comment by chenfeicqq** [comment]
下载后会自动修改 远程链接 为 本地链接的。

这个问题是因为笔记里有多个远程图片，同时下载的时候，通过时间戳生成的文件名一样，除第一个外，其他的保存失败，导致不会执行到修改链接。

问题已修复，升级到 1.1.3 试下

https://github.com/chenfeicqq/obsidian-attachment-manager/releases/tag/1.1.3
